name: ais_taxi
description: "AIS-TAXI — ride-hailing mobile app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.4.3
  stomp_dart_client: ^2.0.0

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  flutter_polyline_points: ^3.1.0

  # UI
  google_fonts: ^6.2.1

  # Storage & Security
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
